# Generated by Django 5.2.6 on 2025-09-11 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_rich_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='rich_content',
        ),
        migrations.AddField(
            model_name='post',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
