# Generated by Django 5.2.6 on 2025-09-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_rich_content_post_reviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='review_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
