# Generated by Django 5.2.7 on 2025-11-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_meta_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='audio_duration',
            field=models.PositiveIntegerField(blank=True, help_text='Duration in seconds', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='audio_file',
            field=models.FileField(blank=True, help_text='Upload an audio file', null=True, upload_to='blog/audio/'),
        ),
    ]
