# Generated by Django 5.2.7 on 2025-11-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_audio_duration_post_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Optional subtitle or tagline', max_length=250),
        ),
    ]
