# Generated by Django 5.2.7 on 2025-11-24 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=models.TextField(blank=True, help_text='Brief summary or teaser of the post (max 500 characters)', max_length=500),
        ),
    ]
