# Generated by Django 5.2.7 on 2025-12-09 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_excerpt'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g., 'Estoy comiendo', 'Example 1', 'Pronunciation'", max_length=200)),
                ('audio_file', models.FileField(help_text='Upload audio file (MP3, WAV, OGG, M4A)', upload_to='blog/audio/')),
                ('audio_duration', models.PositiveIntegerField(blank=True, help_text='Duration in seconds (optional)', null=True)),
                ('description', models.CharField(blank=True, help_text='Optional description or context for this audio', max_length=500)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_files', to='blog.post')),
            ],
            options={
                'verbose_name': 'Post Audio File',
                'verbose_name_plural': 'Post Audio Files',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
