# Generated by Django 5.2.3 on 2025-08-05 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DifficultyLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('level_number', models.PositiveSmallIntegerField(unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['level_number'],
            },
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Brief description or summary of the reader')),
                ('content', models.TextField(help_text='The full text content of the reader')),
                ('publication_date', models.DateField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='reader_covers/')),
                ('word_count', models.PositiveIntegerField(help_text='Total words in the reader')),
                ('vocabulary_focus', models.CharField(blank=True, help_text='Key vocabulary themes', max_length=255)),
                ('grammar_focus', models.CharField(blank=True, help_text='Key grammar concepts', max_length=255)),
                ('difficulty_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readers', to='readers.difficultylevel')),
            ],
            options={
                'ordering': ['difficulty_level__level_number', 'title'],
            },
        ),
    ]
