# Generated by Django 5.2.3 on 2025-08-01 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThematicCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Thematic Category',
                'verbose_name_plural': 'Thematic Categories',
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, unique=True)),
                ('definition', models.TextField()),
                ('gender', models.CharField(choices=[('M', 'Masculine'), ('F', 'Feminine'), ('N', 'None')], default='N', help_text='Gender of the word (if applicable)', max_length=1)),
                ('has_gender', models.BooleanField(default=False, help_text='Check if this word has grammatical gender')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thematic_categories', models.ManyToManyField(blank=True, help_text='Thematic categories this word belongs to', related_name='words', to='temario.thematiccategory')),
            ],
        ),
        migrations.CreateModel(
            name='ExampleSentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='The example sentence in Spanish')),
                ('translation', models.TextField(blank=True, help_text='English translation of the example', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='example_sentences', to='temario.word')),
            ],
        ),
    ]
