# Generated by Django 5.2.3 on 2025-08-01 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='text',
            field=models.CharField(max_length=100),
        ),
    ]
